### ISSUE TITLE
log and migration path

### ISSUE THREAD

**Issue by blondie63** [kitloong/laravel-migrations-generator#177]
Hi, i've tried this command:
php artisan migrate:generate --tables=“companies” —path=/app/database/migrations/tmp/
Using connection: mysql

Generating migrations for: 

 Do you want to log these migrations in the migrations table? (yes/no) [yes]:
 > 

 Next Batch Number is: 8. We recommend using Batch Number 0 so that it becomes the "first" migration. [Default: 0] [0]:
 > 

Setting up Tables and Index migrations.

Setting up Views migrations.

Setting up Stored Procedures migrations.

Setting up Foreign Key migrations.

Finished!

**The response is OK  but no migration is created and also no logs
Whats wrong ?**

 - DB: [MariaDB]
 - DB Version: [10.6.12]
 - Laravel Version: 10.5.0
 - PHP Version: 8.2.3
 - Migrations Generator Version: 6.1.0
 - Doctrine DBAL Version [3.6.1]:

Thanks

**Comment by kitloong** [comment]
Hi @blondie63 

Please review your command:

```
php artisan migrate:generate --tables=“companies” —path=/app/database/migrations/tmp/
```

The hyphen you used for `—path` is not correct.

**Comment by blondie63** [comment]
Ok thanks, anyway the return message is wrong, why no error ? :)

**Comment by kitloong** [comment]
Hi @blondie63 , thanks for reply.

First of all, this is not the correct way to use shortcut option

```
php artisan migrate:generate -t=“companies” -p=/app/database/migrations/tmp
```

Please read https://laravel.com/docs/10.x/artisan#option-shortcuts

Second, you are using wrong double quote `“`
```
php artisan migrate:generate --tables=“companies” --path=/app/database/migrations/tmp
```

Please use `"`

In fact, you can use options without `"`, please read https://laravel.com/docs/10.x/artisan#options-with-values

Finally, if you are using the correct command, it should be like the following:

```
php artisan migrate:generate --tables="not_found" --path=/app/database/migrations/tmp
```

Because you are providing a "not exists" table name, the generator complete the process without any migration file is expected.

However, I do agree a better message can provide clearer feedback to the user.
I will consider update the message in near future.

**Comment by blondie63** [comment]
Ok using the right quote generation is ok but on your docs example you wrote:
--path=/app/database/migrations
this path seems to imply that he is using a relative path when in fact he is using an absolute one, maybe you should update the documentation

Normally the user who uses this generator is on the root of the application and therefore the most correct command should be this:

php artisan migrate:generate --tables="companies" --path=database/migrations/tmp

Do you agree ?

**Comment by kitloong** [comment]
@blondie63  Thanks for pointing out.

However, where do you read this?

```
--path=/app/database/migrations
```

I do not find this from the `README.md`, could you please share with me the link?

Anyway, it is up to the user to use absolute or relative path, you can set the `--path` value on your demand.

**Comment by kitloong** [comment]
This issue is being closed as there has been no response from the author.
