### ISSUE TITLE
Migrations generated for another connection are logged in the wrong connection

### ISSUE THREAD

**Issue by ArnoHolo** [kitloong/laravel-migrations-generator#6]
Hello,

Current behaviour

When you generate migrations for another connection, and chose to log these migrations in the migrations table, they are logged in the migrations table of the other connection.

Expected behaviour

When you generate migrations for another connection, and chose to log these migrations in the migrations table, they should be logged in the migrations table of the default connection. (This is actually what happens when you run the `php artisan migrate` command for a migration related to a connection that is not the default one.)

I use the 7.0 version of laravel/framework.

Thank you!

**Comment by kitloong** [comment]
The current behaviour has been there since log migrations feature first implemented.

Instead of changing it, I have added an option for users to choose whether to log migrations into specified or default connection.

This option only available when user specify connection other than default connection.
