### ISSUE TITLE
 Unknown database type xml requested, Doctrine\DBAL\Platforms\SQLServer2012Platform may not support it.

### ISSUE THREAD

**Issue by Philb27** [kitloong/laravel-migrations-generator#61]
Hi 
Installed on Laravel 8 with an SQL server I keep getting the following error when trying to generate migrations. 

Unknown database type xml requested, Doctrine\DBAL\Platforms\SQLServer2012Platform may not support it.

Any assistance would be appreciated. Thanks

**Comment by kitloong** [comment]
Hi @Philb27

Thank you for reporting.

Mostly, this error happens when `doctrine/dbal` does not recognize data type from the DB platform, in this case, `xml`.
To handle this, I need to register `xml` type and generate with something that Laravel supported. https://laravel.com/docs/8.x/migrations#available-column-types

I am thinking `text` as a replacement for this.

I will proceed with `text` but please let me know if you have a better alternative.
Last but not least, welcome to create PR for this.
