### ISSUE TITLE
The tool is generating a Table instance for every table in the database even if they are not requested

### ISSUE THREAD

**Issue by lsalazarm99** [kitloong/laravel-migrations-generator#68]
Since version 5, we are getting RAM-related errors because the tool is trying to instantiate a `Table` class for each table in our database. Normally, I guess, that should not be a problem. But we have some databases with more than 50k tables and views.

I'm specifying which tables should be generated (less than 100), but I noticed in the code of the tool that it first (1) gets the names of all the tables of the database, then (2) it gets the "details" of each of them, one by one, and finally (3) it filters the tables according to what we specify in the command's parameters.

Shouldn't step 3 happen before step 2 so it only the details of the tables we specified?

In version 4, we didn't have this problem.

For reference, [this](https://github.com/kitloong/laravel-migrations-generator/blob/ded1b97a12db0f405e142f4eb6505fb426e148f8/src/MigrationsGenerator/MigrateGenerateCommand.php#L140) is the method that does the "get the tables and filter them" job.

**Comment by kitloong** [comment]
Hi @lsalazarm99 

Thank you for reporting the issue with the detailed information.
I am sorry the generator has a memory issue in getting the table names.

The updated flow is:
1. Get all table names and filter table by `tables`, `ignore` arguments.
2. Get the table details, then write them into the migration file, one by one.
3. Each table memory is freed after written into the migration file.

This issue should have been fixed in  [v5.1.2](https://github.com/kitloong/laravel-migrations-generator/releases/tag/v5.1.2)

However, if you still facing the problem, feel free to reopen this issue.

Thank you!
