### ISSUE TITLE
Error while generating migration from MSSQL server

### ISSUE THREAD

**Issue by Jagdish-J-P** [kitloong/laravel-migrations-generator#78]
1.  Money column should be converted to double type instead of integer.
2. Column with special characters like . or white space should be handled.

**Comment by kitloong** [comment]
Thank you for your additional info.

1. `money` and `smallmoney` will now generated as `decimal(19,4)` and `decimal(10,4)` respectively.
2. Columns with special characters like . or white space are tested and should be supported.

**Comment by Jagdish-J-P** [comment]
Have you tried generating migration from MSSQL with name.dot column and run that migration on pgsql server?

**Comment by kitloong** [comment]
Running migration with column name `name.dot` on `mysql` and `pgsql` server will fail.

Put the generator outside, if you manually prepare the migration you will have the same error too.
```
$table->string('name.dot');
```

This is out of what the generator can do unless we know the way to escape the special character so that the framework can run and migrate correctly.

If you happen to know please give me the working migration template, and PR is always welcome!

**Comment by Jagdish-J-P** [comment]
I think I can handle it in different way. But for that I need to work on it and currently I am having other projects. Will submit PR soon.
