### ISSUE TITLE
SQLite Database

### ISSUE THREAD

**Issue by mMaJames9** [kitloong/laravel-migrations-generator#86]
Please, how can I generate migrations from a SQLite database ?
I installed the package, but when I run the command `php artisan migrate:generate`, I get this error: **Undefined index: SQLite**

**Comment by kitloong** [comment]
Hi @mMaJames9 ,

Currently `sqlite` is not supported. I will keep this issue open for future enhancement

**Comment by kitloong** [comment]
The generator generates all tables and then adds foreign keys to existing tables. 
However, `sqlite` doesn't support adding foreign keys to the existing table.

See:
1. https://www.sqlite.org/omitted.html
2. https://github.com/laravel/framework/issues/24876
3. https://laravel.com/docs/9.x/migrations#toggling-foreign-key-constraints

For the current workaround, the `add_foreign_key` migrations will still be generated, an additional warning message will be prompted in the command line to remind the user the `add_foreign_key` migrations will not work as expected due to the `sqlite` constraint.

**Comment by kitloong** [comment]
Release with tag `v6.1.0`
