### ISSUE TITLE
Incorrectly mapping tinyint(1) to boolean

### ISSUE THREAD

**Issue by plweller3** [kitloong/laravel-migrations-generator#9]
There appears to be a bad assumption made here that just because Laravel maps boolean to MySQL tinyint(1), that ALL occurrences of tinyint(1) in the database should be mapped back to boolean in the migration files.

Tinyints can represent any signed value between -128 and 127, and people use it as such.  They should NOT be mapped back to boolean.

**Comment by kitloong** [comment]
Hi @plweller3, thank you for your comment.

I am aware of `TINYINT(1)` => `BOOLEAN` behaviour and I am agreed with you not all `TINYINT(1)` equivalant to `BOOLEAN`.

However what supported me to maintain current behaviour is not only because of how Laravel map boolean to `TINYINT(1)`, but also this is the official MySQL asumption:

https://dev.mysql.com/doc/refman/5.7/en/numeric-type-syntax.html
   > BOOL, BOOLEAN
   > These types are synonyms for TINYINT(1).

When you are designing a MySQL schema, a common practice will be:
1. If you are declaring boolean field, use `TINYINT(1)`.
1. If you are declaring a `TINYINT` field (**not for boolean**), use `TINYINT(1+N)`
